/**
 * Idempotent append-if-missing tests for the include line appended to
 * locations.conf (NOT a wildcard conf.d drop -- box-verified on the box).
 *
 * TDD: written before locations-append.ts exists -> RED first.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { buildIncludeLine, ensureIncludeAppended } from '../locations-append.js';

describe('buildIncludeLine', () => {
  it('builds a single include directive for the given include path', () => {
    expect(buildIncludeLine('/boot/config/plugins/u-manager-companion/nginx/companion.conf')).toBe(
      'include /boot/config/plugins/u-manager-companion/nginx/companion.conf;',
    );
  });
});

describe('ensureIncludeAppended', () => {
  let dir: string;
  let locationsConfPath: string;
  const includePath = '/plugin/owned/companion.conf';

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'companion-locations-'));
    locationsConfPath = join(dir, 'locations.conf');
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('appends the include line when locations.conf has none of it', () => {
    writeFileSync(locationsConfPath, '# generated by rc.nginx\ninclude /etc/nginx/conf.d/other.conf;\n');

    const changed = ensureIncludeAppended({ locationsConfPath, includePath });

    expect(changed).toBe(true);
    const content = readFileSync(locationsConfPath, 'utf8');
    expect(content).toContain('include /plugin/owned/companion.conf;');
    expect(content).toContain('include /etc/nginx/conf.d/other.conf;');
  });

  it('is idempotent -- does not duplicate the line on repeated runs', () => {
    writeFileSync(locationsConfPath, '# generated by rc.nginx\n');

    ensureIncludeAppended({ locationsConfPath, includePath });
    const secondRunChanged = ensureIncludeAppended({ locationsConfPath, includePath });

    const content = readFileSync(locationsConfPath, 'utf8');
    const occurrences = content.split('include /plugin/owned/companion.conf;').length - 1;
    expect(occurrences).toBe(1);
    expect(secondRunChanged).toBe(false);
  });

  it('creates locations.conf if it does not exist yet', () => {
    const changed = ensureIncludeAppended({ locationsConfPath, includePath });

    expect(changed).toBe(true);
    const content = readFileSync(locationsConfPath, 'utf8');
    expect(content).toContain('include /plugin/owned/companion.conf;');
  });

  it('detects the line is present even with different surrounding whitespace', () => {
    writeFileSync(locationsConfPath, '   include /plugin/owned/companion.conf;   \n');

    const changed = ensureIncludeAppended({ locationsConfPath, includePath });

    expect(changed).toBe(false);
  });
});
