/**
 * Self-heal monitor tests -- in-process fs monitor on
 * locations.conf, re-appends + validated-reloads when our include line is
 * missing (post-regeneration by rc.nginx). Debounced
 * to avoid reload storms.
 *
 * TDD: written before self-heal-monitor.ts exists -> RED first.
 *
 * The monitor is built on an injectable "watch" primitive rather than
 * node:fs.watch directly, so tests can drive change events deterministically
 * without depending on real filesystem event timing/debouncing quirks.
 */
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { startSelfHealMonitor } from '../self-heal-monitor.js';

describe('startSelfHealMonitor', () => {
  let dir: string;
  let locationsConfPath: string;
  const includePath = '/plugin/owned/companion.conf';

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'companion-self-heal-'));
    locationsConfPath = join(dir, 'locations.conf');
    writeFileSync(locationsConfPath, `include ${includePath};\n`);
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function makeFakeWatcher() {
    let onChangeCallback: (() => void) | undefined;
    const close = vi.fn();
    const watch = vi.fn((_path: string, onChange: () => void) => {
      onChangeCallback = onChange;
      return { close };
    });
    return {
      watch,
      close,
      trigger: () => {
        onChangeCallback?.();
      },
    };
  }

  it('does nothing when the include line is still present after a change event', async () => {
    const fakeWatcher = makeFakeWatcher();
    const heal = vi.fn().mockResolvedValue(undefined);

    startSelfHealMonitor({
      locationsConfPath,
      includePath,
      watchFile: fakeWatcher.watch,
      heal,
      debounceMs: 0,
    });

    fakeWatcher.trigger();
    await vi.waitFor(() => expect(heal).not.toHaveBeenCalled(), { timeout: 500 });
  });

  it('re-appends and heals when the include line disappears (regeneration wiped it)', async () => {
    const fakeWatcher = makeFakeWatcher();
    const heal = vi.fn().mockResolvedValue(undefined);

    startSelfHealMonitor({
      locationsConfPath,
      includePath,
      watchFile: fakeWatcher.watch,
      heal,
      debounceMs: 0,
    });

    // Simulate rc.nginx regenerating locations.conf without our line.
    writeFileSync(locationsConfPath, '# regenerated by rc.nginx\n');
    fakeWatcher.trigger();

    await vi.waitFor(() => expect(heal).toHaveBeenCalledTimes(1), { timeout: 500 });
  });

  it('debounces bursts of change events into a single heal call', async () => {
    const fakeWatcher = makeFakeWatcher();
    const heal = vi.fn().mockResolvedValue(undefined);

    startSelfHealMonitor({
      locationsConfPath,
      includePath,
      watchFile: fakeWatcher.watch,
      heal,
      debounceMs: 50,
    });

    writeFileSync(locationsConfPath, '# regenerated\n');
    fakeWatcher.trigger();
    fakeWatcher.trigger();
    fakeWatcher.trigger();

    await vi.waitFor(() => expect(heal).toHaveBeenCalledTimes(1), { timeout: 1000 });
  });

  it('close() stops watching', () => {
    const fakeWatcher = makeFakeWatcher();
    const heal = vi.fn().mockResolvedValue(undefined);

    const monitor = startSelfHealMonitor({
      locationsConfPath,
      includePath,
      watchFile: fakeWatcher.watch,
      heal,
      debounceMs: 0,
    });

    monitor.close();

    expect(fakeWatcher.close).toHaveBeenCalled();
  });
});
