/**
 * Uninstall cleanup path tests -- remove the include file,
 * strip the appended include line from locations.conf, and validated
 * reload.
 *
 * TDD: written before uninstall.ts exists -> RED first.
 */
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { uninstallNginxIntegration } from '../uninstall.js';

describe('uninstallNginxIntegration', () => {
  let dir: string;
  let includePath: string;
  let locationsConfPath: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'companion-uninstall-'));
    includePath = join(dir, 'companion.conf');
    locationsConfPath = join(dir, 'locations.conf');
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('removes the include file', async () => {
    writeFileSync(includePath, 'location /companion/graphql { }\n');
    writeFileSync(locationsConfPath, `include ${includePath};\n`);
    const runNginx = vi.fn().mockResolvedValue({ exitCode: 0, stdout: '', stderr: '' });

    await uninstallNginxIntegration({
      includePath,
      locationsConfPath,
      nginxBinaryPath: '/usr/sbin/nginx',
      runNginx,
    });

    expect(existsSync(includePath)).toBe(false);
  });

  it('strips the appended include line from locations.conf, preserving other lines', async () => {
    writeFileSync(includePath, 'location /companion/graphql { }\n');
    writeFileSync(
      locationsConfPath,
      `# generated by rc.nginx\ninclude /etc/nginx/conf.d/other.conf;\ninclude ${includePath};\n`,
    );
    const runNginx = vi.fn().mockResolvedValue({ exitCode: 0, stdout: '', stderr: '' });

    await uninstallNginxIntegration({
      includePath,
      locationsConfPath,
      nginxBinaryPath: '/usr/sbin/nginx',
      runNginx,
    });

    const content = readFileSync(locationsConfPath, 'utf8');
    expect(content).not.toContain(`include ${includePath};`);
    expect(content).toContain('include /etc/nginx/conf.d/other.conf;');
  });

  it('runs a validated reload after stripping (nginx -t then -s reload)', async () => {
    writeFileSync(includePath, 'location /companion/graphql { }\n');
    writeFileSync(locationsConfPath, `include ${includePath};\n`);
    const runNginx = vi.fn().mockResolvedValue({ exitCode: 0, stdout: '', stderr: '' });

    await uninstallNginxIntegration({
      includePath,
      locationsConfPath,
      nginxBinaryPath: '/usr/sbin/nginx',
      runNginx,
    });

    expect(runNginx).toHaveBeenCalledWith('/usr/sbin/nginx', ['-t']);
    expect(runNginx).toHaveBeenCalledWith('/usr/sbin/nginx', ['-s', 'reload']);
  });

  it('is a no-op-safe when the include file is already absent', async () => {
    writeFileSync(locationsConfPath, `include ${includePath};\n`);
    const runNginx = vi.fn().mockResolvedValue({ exitCode: 0, stdout: '', stderr: '' });

    await expect(
      uninstallNginxIntegration({
        includePath,
        locationsConfPath,
        nginxBinaryPath: '/usr/sbin/nginx',
        runNginx,
      }),
    ).resolves.not.toThrow();

    expect(existsSync(includePath)).toBe(false);
  });

  it('is a no-op-safe when locations.conf is already absent', async () => {
    writeFileSync(includePath, 'location /companion/graphql { }\n');
    const runNginx = vi.fn().mockResolvedValue({ exitCode: 0, stdout: '', stderr: '' });

    await expect(
      uninstallNginxIntegration({
        includePath,
        locationsConfPath,
        nginxBinaryPath: '/usr/sbin/nginx',
        runNginx,
      }),
    ).resolves.not.toThrow();
  });
});
