/**
 * Idempotent append-if-missing of our include line to locations.conf.
 *
 * Box-verified: there is NO wildcard `include conf.d/*.conf`. locations.conf
 * is GENERATED by /etc/rc.d/rc.nginx on start/renew/update, and any foreign
 * content appended to it is WIPED on regeneration. That means this append is
 * NOT a one-time install step -- it is re-run by the self-heal monitor
 * (self-heal-monitor.ts) every time regeneration is detected. This module
 * only owns the "make sure the line is there" primitive; callers decide
 * when to call it and follow up with a validated reload.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

export interface EnsureIncludeAppendedOptions {
  /** Path to the platform-generated locations.conf (injectable for tests). */
  readonly locationsConfPath: string;
  /** Absolute path to our plugin-owned include file. */
  readonly includePath: string;
}

/** Builds the single `include <path>;` directive appended to locations.conf. */
export function buildIncludeLine(includePath: string): string {
  return `include ${includePath};`;
}

/**
 * Ensures the include line is present in locations.conf, appending it if
 * missing. Idempotent: re-running against a file that already has the line
 * (regardless of surrounding whitespace) is a no-op.
 *
 * Returns `true` if the file was modified, `false` if the line was already
 * present. Callers use this to decide whether a validated reload is needed.
 */
export function ensureIncludeAppended(options: EnsureIncludeAppendedOptions): boolean {
  const { locationsConfPath, includePath } = options;
  const includeLine = buildIncludeLine(includePath);

  const existingContent = existsSync(locationsConfPath)
    ? readFileSync(locationsConfPath, 'utf8')
    : '';

  const alreadyPresent = existingContent
    .split('\n')
    .some((line) => line.trim() === includeLine);

  if (alreadyPresent) {
    return false;
  }

  const needsNewline = existingContent.length > 0 && !existingContent.endsWith('\n');
  const separator = needsNewline ? '\n' : '';
  const nextContent = `${existingContent}${separator}${includeLine}\n`;

  writeFileSync(locationsConfPath, nextContent);
  return true;
}
