/**
 * In-process self-heal monitor for locations.conf.
 *
 * Verified on the box: locations.conf is GENERATED by
 * /etc/rc.d/rc.nginx on start/renew/update, and foreign content appended to
 * it is WIPED on regeneration. The service therefore owns its own
 * reachability: it watches locations.conf and, whenever our include line is
 * found missing after a change event, re-appends it and runs a validated
 * reload. This replaces the shell `inotifywait` watcher for this concern
 * (the bundle watcher.sh stays only for legacy patches).
 *
 * `watchFile` and `heal` are both injectable so tests never depend on real
 * filesystem event timing -- production wiring (server.ts) passes
 * `watchLocationsConfWithFs` and a heal callback composing
 * ensureIncludeAppended + validatedReload.
 */
import { watch as fsWatch, readFileSync } from 'node:fs';
import { buildIncludeLine } from './locations-append.js';

export interface WatcherHandle {
  readonly close: () => void;
}

/** Injectable fs-watch primitive: (path, onChange) -> handle with close(). */
export type WatchFile = (path: string, onChange: () => void) => WatcherHandle;

export interface SelfHealMonitorOptions {
  /** Path to the platform-generated locations.conf. */
  readonly locationsConfPath: string;
  /** Absolute path to our plugin-owned include file (for the line check). */
  readonly includePath: string;
  /** Injectable watch primitive (real fs.watch in production, fake in tests). */
  readonly watchFile: WatchFile;
  /** Called when the include line is found missing -- re-append + reload. */
  readonly heal: () => Promise<void>;
  /** Debounce window in ms to collapse event bursts into one heal (default 500ms). */
  readonly debounceMs?: number;
}

export interface SelfHealMonitor {
  readonly close: () => void;
}

function includeLineIsPresent(locationsConfPath: string, includePath: string): boolean {
  const includeLine = buildIncludeLine(includePath);
  let content: string;
  try {
    content = readFileSync(locationsConfPath, 'utf8');
  } catch {
    // If locations.conf itself is (transiently) missing during a rc.nginx
    // regeneration window, treat that as "not present" -- the next event
    // after regeneration completes will re-check.
    return false;
  }
  return content.split('\n').some((line) => line.trim() === includeLine);
}

/**
 * Starts watching locations.conf. On each (debounced) change event, checks
 * whether our include line is still present; if not, invokes `heal`.
 */
export function startSelfHealMonitor(options: SelfHealMonitorOptions): SelfHealMonitor {
  const { locationsConfPath, includePath, watchFile, heal, debounceMs = 500 } = options;

  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  const onChange = (): void => {
    if (debounceTimer) {
      clearTimeout(debounceTimer);
    }
    debounceTimer = setTimeout(() => {
      debounceTimer = undefined;
      if (!includeLineIsPresent(locationsConfPath, includePath)) {
        void heal();
      }
    }, debounceMs);
    // Debounce timers must not keep the process alive on their own.
    debounceTimer.unref?.();
  };

  const watcher = watchFile(locationsConfPath, onChange);

  return {
    close: () => {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }
      watcher.close();
    },
  };
}

/**
 * Production watch primitive: wraps node:fs.watch on locations.conf.
 * `fs.watch` reliability on FAT/rootfs-regenerated paths is not guaranteed
 * (same caveat noted for the key-store fs-watch) -- this is a
 * best-effort acceleration layered on top of whatever polling / explicit
 * ensure-include calls the startup sequence already performs.
 */
export function watchLocationsConfWithFs(path: string, onChange: () => void): WatcherHandle {
  const watcher = fsWatch(path, { persistent: false }, () => {
    onChange();
  });
  return {
    close: () => {
      watcher.close();
    },
  };
}
